version: 1.0.21.{build}

os: Visual Studio 2017

environment:
  matrix:
    - platform: x64
      configuration: ReleaseDLL

matrix:
  fast_finish: false

init: msbuild /version

build:
  parallel: true
  project: ci/appveyor/libsodium.vcxproj
  verbosity: minimal

artifacts:
  - path: ci/appveyor/Build/%configuration%/%platform%/libsodium.dll
